# coding=UTF-8
from typing import Optional, Protocol, runtime_checkable

import asyncio


@runtime_checkable
class IWebUiOperations(Protocol):
    def list_watches(self) -> list: ...
    def create_watch(self, payload: dict) -> dict: ...
    def update_watch(self, watch_id: str, payload: dict) -> dict: ...
    def delete_watch(self, watch_id: str) -> bool: ...
    def list_watch_events(self, watch_id: str, limit: int = 50, offset: int = 0) -> Optional[dict]: ...
    def delete_web_task(self, task_id: int) -> bool: ...
    def pause_web_task(self, task_id: int) -> bool: ...
    def resume_web_task(self, task_id: int) -> bool: ...
    def retry_failed_web_task(self, task_id: int) -> int: ...
    def submit_web_task(self, task_id: int) -> None: ...
    def statistics(self) -> dict: ...
    def export_table(self, table_type: str) -> dict: ...
    def create_upload(self, payload: dict) -> dict: ...
    def create_channel_download(self, payload: dict) -> dict: ...
    def detect_transfer_range(self, source_link: str) -> Optional[tuple]: ...
    def scan_media_for_cleanup(self, task_id: int = None) -> dict: ...
    def cleanup_media_files(self, payload: dict) -> dict: ...
    def list_cleanup_logs(self) -> list: ...


@runtime_checkable
class IUploadContext(Protocol):
    """Focused upload dependencies: config, loop, progress, diagnostics, lifetime."""
    app: object
    loop: asyncio.AbstractEventLoop
    pb: object
    done_notice: object
    my_id: int
    is_running: bool
    is_bot_running: bool
    web_ui: Optional[object]
    wait_for_telegram_flood: object
    diagnostic: object


@runtime_checkable
class IDiagnosticPort(Protocol):
    def info(self, message: str, *args, **kwargs) -> None: ...
    def warning(self, message: str, *args, **kwargs) -> None: ...
    def error(self, message: str, *args, **kwargs) -> None: ...
    def debug(self, message: str, *args, **kwargs) -> None: ...
    def exception(self, message: str, *args, **kwargs) -> None: ...
    def console_log(self, *args, **kwargs) -> None: ...
    def console_print(self, *args, **kwargs) -> None: ...


@runtime_checkable
class ILiveWatchContext(Protocol):
    listen_download_chat: dict
    listen_forward_chat: dict
    web_pending_watches: dict
    web_watch_handler_clients: dict
    user: object
    app: object
    transfer_store: object

    def persisted_watches(self) -> list: ...
    def download_watch_id(self, link: str) -> str: ...
    def forward_watch_id(self, rule: str) -> str: ...
    def set_live_watch_status(self, watch_id: str, status: str, error_message: str = None) -> None: ...
    def watch_payload_from_record(self, record: dict) -> dict: ...
    def persist_watch(self, watch: dict) -> dict: ...
    def submit_web_operation(self, op_type: str, payload: dict) -> dict: ...
