# coding=UTF-8
"""Shared TransferStore class constants used by mixin default arguments."""

DEFAULT_MAINTENANCE_MIN_INTERVAL_SECONDS = 6 * 60 * 60
DEFAULT_RECONCILE_MIN_INTERVAL_SECONDS = 60
STALE_TRANSFER_ITEM_TIMEOUT_SECONDS = 5 * 60
STALE_EMPTY_WATCH_INLINE_TIMEOUT_SECONDS = 10 * 60
DEFAULT_EVENT_PURGE_MIN_INTERVAL_SECONDS = 7 * 24 * 60 * 60
TRANSFER_EVENTS_RETENTION_DAYS = 90
LIVE_WATCH_EVENTS_RETENTION_DAYS = 30
CLEANUP_LOG_RETENTION_DAYS = 30
SYSTEM_LOGS_RETENTION_DAYS = 2
VACUUM_FREE_PAGE_THRESHOLD = 512
